-- GrowSorcio -> Supabase migration base
-- Run this SQL in Supabase SQL Editor.

create extension if not exists pgcrypto;

-- Core tenants table
create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Profile linked to auth.users
create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  full_name text,
  role text not null default 'member' check (role in ('owner', 'admin', 'member')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  nome text not null,
  whatsapp text,
  email text,
  instagram text,
  tipo_de_bem text,
  valor_da_carta numeric(14, 2),
  recurso_para_lance numeric(14, 2),
  restricao_cpf boolean not null default false,
  urgencia text,
  temperatura text not null default 'frio' check (temperatura in ('frio', 'morno', 'quente')),
  etapa_funil text not null default 'Lead Novo',
  motivo_descarte text,
  snooze_ate date,
  data_proxima_acao date,
  tipo_proxima_acao text,
  observacoes text,
  origem text not null default 'prospeccao' check (origem in ('prospeccao', 'anuncio')),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.interacoes (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  lead_id bigint not null references public.leads(id) on delete cascade,
  data date not null,
  tipo text not null,
  descricao text not null,
  proxima_acao text,
  criado_em timestamptz not null default now()
);

create table if not exists public.cadencia_itens (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  lead_id bigint not null references public.leads(id) on delete cascade,
  descricao text not null,
  data_prevista date,
  concluido boolean not null default false,
  etapa_relacionada text,
  criado_em timestamptz not null default now()
);

create index if not exists leads_org_idx on public.leads (organization_id);
create index if not exists leads_org_etapa_idx on public.leads (organization_id, etapa_funil);
create index if not exists leads_org_temp_idx on public.leads (organization_id, temperatura);
create index if not exists leads_org_origem_idx on public.leads (organization_id, origem);
create index if not exists leads_org_proxima_acao_idx on public.leads (organization_id, data_proxima_acao);
create index if not exists interacoes_org_lead_idx on public.interacoes (organization_id, lead_id);
create index if not exists cadencia_org_lead_idx on public.cadencia_itens (organization_id, lead_id);

create unique index if not exists leads_org_whatsapp_unique
  on public.leads (organization_id, whatsapp)
  where whatsapp is not null and whatsapp <> '';

create unique index if not exists leads_org_email_unique
  on public.leads (organization_id, email)
  where email is not null and email <> '';

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger trg_org_updated_at
before update on public.organizations
for each row execute function public.set_updated_at();

create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger trg_leads_updated_at
before update on public.leads
for each row execute function public.set_updated_at();

create or replace function public.set_child_organization_from_lead()
returns trigger
language plpgsql
as $$
declare
  v_org uuid;
begin
  select organization_id into v_org from public.leads where id = new.lead_id;
  if v_org is null then
    raise exception 'Lead % not found when resolving organization', new.lead_id;
  end if;

  if new.organization_id is null then
    new.organization_id = v_org;
  elsif new.organization_id <> v_org then
    raise exception 'organization_id does not match lead organization';
  end if;

  return new;
end;
$$;

create trigger trg_interacoes_org_sync
before insert or update on public.interacoes
for each row execute function public.set_child_organization_from_lead();

create trigger trg_cadencia_org_sync
before insert or update on public.cadencia_itens
for each row execute function public.set_child_organization_from_lead();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_org_id uuid;
  v_name text;
begin
  v_name := coalesce(
    new.raw_user_meta_data->>'company_name',
    new.raw_user_meta_data->>'organization_name',
    new.raw_user_meta_data->>'full_name',
    split_part(new.email, '@', 1),
    'Minha Organizacao'
  );

  insert into public.organizations(name)
  values (v_name)
  returning id into v_org_id;

  insert into public.profiles(user_id, organization_id, full_name, role)
  values (
    new.id,
    v_org_id,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    'owner'
  );

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_org_member(org_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.user_id = auth.uid()
      and p.organization_id = org_id
  );
$$;

create or replace function public.user_role(org_id uuid)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select p.role
  from public.profiles p
  where p.user_id = auth.uid()
    and p.organization_id = org_id
  limit 1;
$$;

alter table public.organizations enable row level security;
alter table public.profiles enable row level security;
alter table public.leads enable row level security;
alter table public.interacoes enable row level security;
alter table public.cadencia_itens enable row level security;

-- Organizations
create policy organizations_select
on public.organizations
for select
to authenticated
using (public.is_org_member(id));

create policy organizations_update_owner_admin
on public.organizations
for update
to authenticated
using (public.user_role(id) in ('owner', 'admin'))
with check (public.user_role(id) in ('owner', 'admin'));

-- Profiles
create policy profiles_select_same_org
on public.profiles
for select
to authenticated
using (public.is_org_member(organization_id));

create policy profiles_update_self_or_admin
on public.profiles
for update
to authenticated
using (auth.uid() = user_id or public.user_role(organization_id) in ('owner', 'admin'))
with check (auth.uid() = user_id or public.user_role(organization_id) in ('owner', 'admin'));

-- Leads
create policy leads_select
on public.leads
for select
to authenticated
using (public.is_org_member(organization_id));

create policy leads_insert
on public.leads
for insert
to authenticated
with check (public.is_org_member(organization_id));

create policy leads_update
on public.leads
for update
to authenticated
using (public.is_org_member(organization_id))
with check (public.is_org_member(organization_id));

create policy leads_delete
on public.leads
for delete
to authenticated
using (public.user_role(organization_id) in ('owner', 'admin'));

-- Interactions
create policy interacoes_select
on public.interacoes
for select
to authenticated
using (public.is_org_member(organization_id));

create policy interacoes_insert
on public.interacoes
for insert
to authenticated
with check (public.is_org_member(organization_id));

create policy interacoes_update
on public.interacoes
for update
to authenticated
using (public.is_org_member(organization_id))
with check (public.is_org_member(organization_id));

create policy interacoes_delete
on public.interacoes
for delete
to authenticated
using (public.is_org_member(organization_id));

-- Cadence items
create policy cadencia_select
on public.cadencia_itens
for select
to authenticated
using (public.is_org_member(organization_id));

create policy cadencia_insert
on public.cadencia_itens
for insert
to authenticated
with check (public.is_org_member(organization_id));

create policy cadencia_update
on public.cadencia_itens
for update
to authenticated
using (public.is_org_member(organization_id))
with check (public.is_org_member(organization_id));

create policy cadencia_delete
on public.cadencia_itens
for delete
to authenticated
using (public.is_org_member(organization_id));

create or replace function public.reset_identity_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform setval(pg_get_serial_sequence('public.leads', 'id'), coalesce((select max(id) from public.leads), 0) + 1, false);
  perform setval(pg_get_serial_sequence('public.interacoes', 'id'), coalesce((select max(id) from public.interacoes), 0) + 1, false);
  perform setval(pg_get_serial_sequence('public.cadencia_itens', 'id'), coalesce((select max(id) from public.cadencia_itens), 0) + 1, false);
end;
$$;
