-- LGPD — Registro de consentimentos e aceites de documentos
-- Guarda: data do aceite, versão do documento, tipo e IP do usuário
-- Retenção: conforme art. 7º LGPD (consentimento registrado como base legal)

create table if not exists public.consent_records (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references auth.users(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  -- Tipo do documento: 'privacy_policy' | 'terms_of_service' | 'cookie_policy'
  document_type    text not null check (document_type in ('privacy_policy', 'terms_of_service', 'cookie_policy')),
  document_version text not null,            -- ex: "2026-03-28"
  accepted_at      timestamptz not null default now(),
  ip_address       inet,                      -- base legal: consentimento registrado
  user_agent       text
);

-- Índices para consultas de portabilidade e auditoria
create index if not exists consent_records_user_idx on public.consent_records (user_id);
create index if not exists consent_records_org_idx  on public.consent_records (organization_id);

-- RLS — isolamento por tenant
alter table public.consent_records enable row level security;

-- Usuário autenticado lê apenas seus próprios registros
create policy "consent_records: select own"
  on public.consent_records
  for select
  using (auth.uid() = user_id);

-- Usuário autenticado insere apenas para si mesmo na sua organização
create policy "consent_records: insert own"
  on public.consent_records
  for insert
  with check (
    auth.uid() = user_id
    and organization_id in (
      select organization_id from public.profiles where user_id = auth.uid()
    )
  );

-- Nenhum update ou delete via RLS — registros de consentimento são imutáveis
-- (para correções, inserir novo registro com versão atualizada)
